export const NOTIFICATION_TYPES = {
    GENERIC: 'GENERIC',
    DEBT_CREATED: 'DEBT_CREATED',
    DEBT_CANCELED_BY_SENDER: 'DEBT_CANCELED_BY_SENDER',
    DEBT_CANCELED_BY_RECEIVER: 'DEBT_CANCELED_BY_RECEIVER',
    DEBT_PAID: 'DEBT_PAID'
};

export default NOTIFICATION_TYPES;
